language: rust
sudo: required
dist: trusty
addons:
  apt:
    packages:
      - libssl-dev
env:
  - PATH=$HOME/.cargo/bin:$PATH
script:
  - cargo test -j2 --all
matrix:
  fast_finish: true
  include:
    - rust: stable
    # Run rustfmt in its own shard.
    - rust: stable
      env:
        - SHARD=rustfmt
      before_script:
        - rustup component add --toolchain stable rustfmt-preview
      script:
        - echo "Checking project codebase with rustfmt release `cargo fmt --version`."
        - cargo fmt --all -- --check
    # Run Clippy in its own shard.
    - rust: stable
      env:
        - SHARD=clippy
      before_script:
        - rustup component add --toolchain stable clippy
      script:
        - echo "Checking project codebase with Clippy release `cargo clippy --version`."
        - cargo clippy --all --profile test
