[package]
name = "wasmer/static-web-server"
version = "1.0.4"
description = "Serves static files in response to HTTP GET and HEAD requests."
license = "MIT"
readme = "README.md"
repository = "https://github.com/wasmerio/static-web-server"
homepage = "https://wasmer.io/wasmer/static-web-server"
wasmer-extra-flags = "--enable-threads --enable-bulk-memory"

[[module]]
name = "webserver"
source = "web-server.wasm"
abi = "wasi"

[[command]]
name = "webserver"
module = "webserver"
runner = "wasi@unstable_"
